//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.03 at 10:49:14 EST 
//


package com.tcs.ain.mp.ppf.jaxb;


/**
 * Java content class for Transaction element declaration.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;element name="Transaction">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;sequence>
 *             &lt;element name="DataArea">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;sequence>
 *                       &lt;element name="Registration" minOccurs="0">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;sequence>
 *                                 &lt;element name="MailingTypes" minOccurs="0">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="RegistrationMailings" minOccurs="0">
 *                                             &lt;complexType>
 *                                               &lt;complexContent>
 *                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                   &lt;sequence>
 *                                                     &lt;element name="RegistrationMailing" maxOccurs="unbounded" minOccurs="0">
 *                                                       &lt;complexType>
 *                                                         &lt;complexContent>
 *                                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                             &lt;sequence>
 *                                                               &lt;element name="regMailingPrimaryKey" minOccurs="0">
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                                   &lt;maxLength value="15"/>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/element>
 *                                                               &lt;element name="mailingRecipientType" minOccurs="0">
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                                   &lt;maxLength value="60"/>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/element>
 *                                                               &lt;element name="receiptCode" minOccurs="0">
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                                   &lt;maxLength value="9"/>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/element>
 *                                                             &lt;/sequence>
 *                                                           &lt;/restriction>
 *                                                         &lt;/complexContent>
 *                                                       &lt;/complexType>
 *                                                     &lt;/element>
 *                                                   &lt;/sequence>
 *                                                 &lt;/restriction>
 *                                               &lt;/complexContent>
 *                                             &lt;/complexType>
 *                                           &lt;/element>
 *                                           &lt;element name="mailingTypeId" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="10"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="mailingTypeCode" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="4"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="mailingTypeName" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="40"/>
 *                                               &lt;enumeration value="Initial Agent Return Receipt Pending"/>
 *                                               &lt;enumeration value="Initial Facility Return Receipt Pending"/>
 *                                               &lt;enumeration value="Initial Agent Assignment Notification"/>
 *                                               &lt;enumeration value="Initial Facility Assignment Notification"/>
 *                                               &lt;enumeration value="Registration Modified by FDA"/>
 *                                               &lt;enumeration value="Registration Cancelled"/>
 *                                               &lt;enumeration value="Transfer of Ownership Notification"/>
 *                                               &lt;enumeration value="Facility Merger Notification"/>
 *                                               &lt;enumeration value="Initial Paper Registration"/>
 *                                               &lt;enumeration value="Facility without US Agent"/>
 *                                               &lt;enumeration value="Agent Re-Assignment"/>
 *                                               &lt;enumeration value="PIN Modification"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="recipient1" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="40"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="recipient2" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="40"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="recipient3" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="40"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="recipient4" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="40"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="mediaCode" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;enumeration value="letter"/>
 *                                               &lt;enumeration value="email"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="timeToRespondCalendarDays" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                           &lt;element name="recurringTimeframeFlag" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="1"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="negativeResponseActionFlag" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="1"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="mailingTypeStatus" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="20"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="mailingTypeStatusDate" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="22"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="mailingDate" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="22"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="responseRequiredFlag" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="20"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="responseSubmitterName" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="60"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="responseSubmitterType" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="30"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="submitterResponse" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="20"/>
 *                                               &lt;enumeration value="Positive"/>
 *                                               &lt;enumeration value="Negative"/>
 *                                               &lt;enumeration value="Missing"/>
 *                                               &lt;enumeration value="Undeliverable Mail"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="recurringCalendarDays" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                                 &lt;element name="MailToAddresses" minOccurs="0">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="MailToAddress" maxOccurs="unbounded" minOccurs="0">
 *                                             &lt;complexType>
 *                                               &lt;complexContent>
 *                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                   &lt;sequence>
 *                                                     &lt;element name="name" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="60"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="addressLine1" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="40"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="addressLine2" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="40"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="city" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="40"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="zipcode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="10"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="stateProvince" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="80"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="email" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="40"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="busPhoneCountryCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="3"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="busPhoneAreaCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="5"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="busPhoneNum" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="15"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="busPhoneExtn" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="6"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="homePhoneCountryCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="3"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="homePhoneAreaCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="5"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="homePhoneNum" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="15"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="faxCountryCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="3"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="faxAreaCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="5"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="faxNum" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="15"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="title" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="40"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="isoCountryCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="2"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="country" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="50"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="receiptCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="9"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="rate" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="15"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                   &lt;/sequence>
 *                                                   &lt;attribute name="addressType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                 &lt;/restriction>
 *                                               &lt;/complexContent>
 *                                             &lt;/complexType>
 *                                           &lt;/element>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                                 &lt;element name="AccountRegistrationLink" minOccurs="0">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="accountNumber" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="32"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="accountName" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="41"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="accountEmail" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="40"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="submitter" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="25"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="linkStatus" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="1"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="linkActivationDate" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="22"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="linkDeactivationDate" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="22"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="accountSeqId" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="11"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                                 &lt;element name="Addresses" minOccurs="0">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="Address" maxOccurs="unbounded" minOccurs="0">
 *                                             &lt;complexType>
 *                                               &lt;complexContent>
 *                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                   &lt;sequence>
 *                                                     &lt;element name="name" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="60"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="addressLine1" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="40"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="addressLine2" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="40"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="city" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="40"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="zipcode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="10"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="stateProvince" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="80"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="email" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="40"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="busPhoneCountryCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="3"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="busPhoneAreaCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="5"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="busPhoneNum" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="15"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="busPhoneExtn" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="6"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="homePhoneCountryCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="3"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="homePhoneAreaCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="5"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="homePhoneNum" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="15"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="faxCountryCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="3"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="faxAreaCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="5"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="faxNum" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="15"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="title" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="40"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="isoCountryCode" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="2"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="country" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="50"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="validateState" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="30"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="matchState" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="30"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="usePostalAddress" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="1"/>
 *                                                         &lt;enumeration value="Y"/>
 *                                                         &lt;enumeration value="N"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                     &lt;element name="sectionFlag" minOccurs="0">
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                         &lt;maxLength value="15"/>
 *                                                         &lt;enumeration value="Section2"/>
 *                                                         &lt;enumeration value="Section3"/>
 *                                                         &lt;enumeration value="Section4"/>
 *                                                         &lt;enumeration value="Section7"/>
 *                                                       &lt;/restriction>
 *                                                     &lt;/element>
 *                                                   &lt;/sequence>
 *                                                   &lt;attribute name="addressType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                 &lt;/restriction>
 *                                               &lt;/complexContent>
 *                                             &lt;/complexType>
 *                                           &lt;/element>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                                 &lt;element name="regNbr" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="16"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="regLocationType" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="D"/>
 *                                     &lt;enumeration value="I"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="pin" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="16"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="alternateTradeName1" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="40"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="alternateTradeName2" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="40"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="alternateTradeName3" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="40"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="alternateTradeName4" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="40"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="seasonDescription" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="40"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="ambientStorageTypeFlag" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="1"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="refrigeratedStorageTypeFlag" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="1"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="frozenStorageTypeFlag" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="1"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="submitter" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="30"/>
 *                                     &lt;enumeration value="Owner/Operator/AIC"/>
 *                                     &lt;enumeration value="Other Authorized Individual"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="regStatus" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="30"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="statusReason" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="75"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="regStatusActivationDt" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="22"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="regStatusDeactivationDt" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="22"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="facilityFeiNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                 &lt;element name="usAgentFeiNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                 &lt;element name="mergFacRegNbr" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="16"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="oldFacilityRegNbr" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="16"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="lastUpdateDate" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="22"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="ppfBarCode" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="30"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="previousOwnersName" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="60"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="previousOwnerFlag" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="1"/>
 *                                     &lt;enumeration value="Y"/>
 *                                     &lt;enumeration value="N"/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="authorizerFlag" minOccurs="0">
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="2"/>
 *                                     &lt;enumeration value="OW"/>
 *                                     &lt;enumeration value="NM"/>
 *                                     &lt;enumeration value=""/>
 *                                   &lt;/restriction>
 *                                 &lt;/element>
 *                                 &lt;element name="EstablishmentTypes" minOccurs="0">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="EstablishmentDesc" maxOccurs="unbounded" minOccurs="0">
 *                                             &lt;complexType>
 *                                               &lt;complexContent>
 *                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                   &lt;sequence>
 *                                                     &lt;element name="estDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                   &lt;/sequence>
 *                                                 &lt;/restriction>
 *                                               &lt;/complexContent>
 *                                             &lt;/complexType>
 *                                           &lt;/element>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                                 &lt;element name="HumanProductList" minOccurs="0">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="ProdHumanDesc" maxOccurs="unbounded" minOccurs="0">
 *                                             &lt;complexType>
 *                                               &lt;complexContent>
 *                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                   &lt;sequence>
 *                                                     &lt;element name="prodHumDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                   &lt;/sequence>
 *                                                 &lt;/restriction>
 *                                               &lt;/complexContent>
 *                                             &lt;/complexType>
 *                                           &lt;/element>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                                 &lt;element name="AnimalProductList" minOccurs="0">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="ProdAnimalDesc" maxOccurs="unbounded" minOccurs="0">
 *                                             &lt;complexType>
 *                                               &lt;complexContent>
 *                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                   &lt;sequence>
 *                                                     &lt;element name="prodAnDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                   &lt;/sequence>
 *                                                 &lt;/restriction>
 *                                               &lt;/complexContent>
 *                                             &lt;/complexType>
 *                                           &lt;/element>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                               &lt;/sequence>
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                       &lt;element name="SimpleTextMailing" minOccurs="0">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;sequence>
 *                                 &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                 &lt;element name="mailcontent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                 &lt;element name="MailingAddress" minOccurs="0">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="firstName" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="20"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="lastName" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="20"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="street" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="80"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="city" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="40"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="state" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="80"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="zipcode" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="10"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                           &lt;element name="countryCode" minOccurs="0">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="50"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                               &lt;/sequence>
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                       &lt;element name="Exceptions" minOccurs="0">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;sequence>
 *                                 &lt;element name="Exception" maxOccurs="unbounded" minOccurs="0">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                           &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                               &lt;/sequence>
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                     &lt;/sequence>
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="ControlArea" minOccurs="0">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;sequence>
 *                       &lt;element name="verb" minOccurs="0">
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="Process Response"/>
 *                           &lt;enumeration value="Process Response Log"/>
 *                           &lt;enumeration value="Mailing Request"/>
 *                           &lt;enumeration value="Mailing Request Email Log"/>
 *                           &lt;enumeration value="Handle Exception"/>
 *                           &lt;enumeration value="Send Email"/>
 *                           &lt;enumeration value="Email Request From Registration Preview"/>
 *                           &lt;enumeration value="Initial Registration"/>
 *                           &lt;enumeration value="Update Registration"/>
 *                           &lt;enumeration value="Cancel Registration"/>
 *                         &lt;/restriction>
 *                       &lt;/element>
 *                       &lt;element name="facilityNameChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                       &lt;element name="facilityAddressChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                       &lt;element name="preferredMailingAddressChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                       &lt;element name="parentCompanyChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                       &lt;element name="emergencyContactChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                       &lt;element name="tradeNameChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                       &lt;element name="unitedStatesAgentChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                       &lt;element name="seasonalFacilityDatesofOperationChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                       &lt;element name="typeOfActivityChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                       &lt;element name="typeOfStorageChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                       &lt;element name="humanFoodProductCategoryChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                       &lt;element name="animalFoodProductCategoryChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                       &lt;element name="operatorOrAgentInChargeChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                       &lt;element name="noun" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                       &lt;element name="PPFReferenceId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                       &lt;element name="Initiator" minOccurs="0">
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="PPF"/>
 *                           &lt;enumeration value="FFRM"/>
 *                           &lt;enumeration value="ACCOUNTMANAGEMENT"/>
 *                         &lt;/restriction>
 *                       &lt;/element>
 *                     &lt;/sequence>
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *           &lt;/sequence>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface Transaction
    extends javax.xml.bind.Element, TransactionType
{


}
